name: Release-Notes

on:
  create:
    tags:
      - 'BUILD-*-*'
  # push:
  #   branches: none # [ main ]
  # pull_request:
  #   branches:  none # [ release ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      currentrelease:
        required: true
      currentreleaseyear:
        required: true
jobs:
  create-branch-PR:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 #install the python needed
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: create-new-branch
        run: |
          git checkout -b releasenotesbranch4
          python template.py ${{ inputs.currentrelease }} ${{ inputs.currentreleaseyear }}
      - name: commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_TITLE="updated the files"
          BRANCH_NAME="releasenotesbranch4"
          git config user.name "srikanthnamoju"
          git config user.email "srikanthnamoju5677@gmail.com"
          git add .
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Creating PR \"$PR_TITLE\" for branch $BRANCH_NAME"
            git commit -m "$PR_TITLE"
            git push origin $BRANCH_NAME
            # gh pr create --title "$PR_TITLE" --body "This is an automated PR to update the files"
            gh pr create -B main -H releasenotesbranch4 --title "$PR_TITLE" --body "This is an automated PR to update the files"
          else
            echo "Looks like there was nothing to update."
          fi
      # - name: commit and push changes
      #   run: |
      #     git push origin --delete releasenotesbranch4
      #   env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      # - name: open pull request
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     token: ${{secrets.GITHUB_TOKEN}}
      #     branch: main
      #     title: releasenotes update
      #     body: "review the changes made to releasenotes files"    
      # - name: create pull request
      #   run: |
      #     gh pr create --base main --head releasenotesbranch4 --title "modified files" --body "Please review the changes"
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      # - name: Delete branch
      #   uses: dawidd6/action-delete-branch@v3
      #   with:
      #     github_token: ${{github.token}}
      #     branches: releasenotesbranch4
